"""upload_token_reminders

Revision ID: 71d3016cc917
Revises: fdbceb410b8d
Create Date: 2023-08-01 20:47:39.435396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d3016cc917'
down_revision = 'fdbceb410b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploadtoken', sa.Column('last_expiration_reminder', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploadtoken', 'last_expiration_reminder')
    # ### end Alembic commands ###
